// This is an autogenerated file from Firebase Studio.
import * as admin from 'firebase-admin';
import { cache } from 'react';

// Initialize Firebase Admin for the server, wrapped in a cached function
const initAdmin = () => {
    if (!admin.apps.length) {
        admin.initializeApp({
            credential: admin.credential.applicationDefault(),
        });
    }
    return admin.firestore();
};

const getAdminDb = cache(initAdmin);

export const adminDb = getAdminDb();
